version: "3.9"
services:
  web:
    build: .
    container_name: "key-value-web"
    command: flask run -h ${HOST} -p ${APP_PORT}
    restart: always
    ports:
      - "8080:${APP_PORT}"
    depends_on:
      - db
    env_file:
      - ./.env
    networks:
      - kv_backend

  db:
    image: mongo:7.0
    container_name: "key-value-db"
    command: mongod --quiet --logpath=/dev/null
    restart: unless-stopped
    networks:
      - kv_backend
    env_file:
      - .env
    volumes:
      - kv_db:/data/db

networks:
  kv_backend:
    driver: bridge

volumes:
  kv_db: {}
